Algoritmo "Conversor de medidas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ízaias
// Descrição   : converte km em metros
// Autor(a)    : Juan Natanael Marques dos Santos
// Data atual  : 12/09/2024
Var
// Seção de Declarações das variáveis 
   km, m: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite a quantidade de KM:")
   leia (km)
   
   m<- km*1000
   
   escreval ("em metros é:", m,"m")

Fimalgoritmo